### ISSUE TITLE
Performance issue with getting scrollbars sizes in scroll strategy.

### ISSUE THREAD

**Issue by gejgalis** [wnr/element-resize-detector#107]
When we have a lot of DOM elements on the page, and then we want to install detector on newly created element we encounter performance hit caused by `getScrollbarSizes()` called within `scroll` strategy.
It is not necessary to measure scrollbars sizes multiple times. I'll provide PR in a minute.

**Comment by wnr** [comment]
Hi,

I'm not opposed to this change. However, it seems like you are using this library in a suboptimal way. In order to get any of the performance improvements that are unique to this library, the elements need to share the same instance of ERD. Some prefer to create a global instance, and others prefer to dependency inject the instance to the components.

**Comment by gejgalis** [comment]
You're right - every time where we need detector we create new instance of erd. Now I switched in our codebase to share common instance and it works perfect!

@wnr you may drop my pull request if you want.

**Comment by wnr** [comment]
Cool :)
