### ISSUE TITLE
[Feature Request] Provide an ECMAScript module (ESM)  bundle

### ISSUE THREAD

**Issue by Lonli-Lokli** [wnr/element-resize-detector#126]
Provide an ECMAScript module (ESM)  bundle instead of only commonJS
ref: https://web.dev/commonjs-larger-bundles/

**Comment by wnr** [comment]
Seems like a good thing! Would you create a PR? :)

**Comment by nachodd** [comment]
I have some issues with this package for the same reason. To put it in context: 
I'm using [vue-grid-layout-v3](https://github.com/merfais/vue-grid-layout-v3/blob/master/src/components/GridLayout.vue#L2) which uses your library. Everything is fine, until I try to use `vue-grid-layout-v3` with Vite, which uses ESM packages under the hood. So it was throwing me errors like "element-resize-detector doesn't have a default export". So, it seems that the problem is that your library is not ESM compatible. I needs a rewrite... OR, maybe we can use a tools like: [to-esm](https://www.npmjs.com/package/to-esm?activeTab=readme) and generate different entry points. 
What do you think? I haven't tried it, but seems promising. If you accept, I can try it.
