### ISSUE TITLE
If container is undefined in isUnrendered calling getComputedStyle will throw

### ISSUE THREAD

**Issue by tkh44** [wnr/element-resize-detector#63]
https://github.com/wnr/element-resize-detector/blob/master/src/detection-strategy/scroll.js#L173

https://github.com/wnr/element-resize-detector/pull/62

**Comment by wnr** [comment]
Hi and thank you for the PR. Could you tell me some more about when this problem occurs? I would like us to construct a failing unit test capturing the problem before accepting the solution. Thanks

**Comment by tkh44** [comment]
I could not pin down the exact issue. It occurred for me when using the the scroll detection strategy with preact.  I suspect it has something to do with its implementation of the dom diffing algorithm reusing dom nodes.

**Comment by wnr** [comment]
Ah, yes that sounds like that it could cause some problems. The element that is being listened to may not be modified freely since the injected elements must be present as direct children to the element. Reusing dom nodes sounds like it could cause such problems. Your fix would stop the system from throwing the error, but the element resize detection behaviour would be undefined (probably it would just stop working). So I think the real solution here is to not modify or reuse the contents of an element that is being listened to for resize events. If you want to stop the listening, call `uninstall` before the element is unmounted.

**Comment by tkh44** [comment]
Ok, thank you for the suggestion
