### ISSUE TITLE
Does not detect element resized due to window resize

### ISSUE THREAD

**Issue by mking-clari** [wnr/element-resize-detector#65]
Note: This is supported by `css-element-queries`.

**Comment by wnr** [comment]
Hi and thanks for the report. I'm unable to reproduce this. Could you share a more detailed example?

**Comment by mking-clari** [comment]
@wnr https://github.com/mking-clari/detect-window-size

Steps to reproduce
1. `npm start`
1. Resize the window
1. In the console, resize is not detected by element-resize-detector and is detected by css-element-queries.

**Comment by wnr** [comment]
Thank you, that's really interesting. I'll look into it.

**Comment by wnr** [comment]
Hi again,

The reason the resize detection stops working is because your CSS makes ALL elements position relative, including the injected detection elements. See line https://github.com/mking-clari/detect-window-size/blob/master/src/foo.scss#L4

It is stated in the API that you may not alter the injected elements in any way. The reason why this project fails and not the css-element-queries is because this project also supports inline elements, which requires a bit more advanced method. I'll see if it possible to make the method more resilient to such CSS, but I would recommend you not to make such global rules.
